### PR TITLE
Pre-Loader Added

### PR DESCRIPTION
**Pull request by khushimarothi**
#61 resolved.

### CODE REVIEW

**Comment by nisha331** [comment]
@khushimarothi plz provide vdo or screenshort

**Comment by khushimarothi** [comment]
Screenshot (8)

**Comment by khushimarothi** [comment]
here it is please check your dm too , I have some doubts.

**Review by nisha331 — APPROVED** [review]

**Comment by khushimarothi** [comment]
can you reopen this PR. I just checked the deployment and noticed that the gif is not pushed so a blank page is appearing.

**Pull request merged**
