### PR TITLE
added ovulation.html and ovulation.css

### PR DESCRIPTION
**Pull request by Tushar-go**
#29

### CODE REVIEW

**Comment by nisha331** [comment]
Can I see some images or vdos  @Tushar-go

**Comment by Tushar-go** [comment]
> Can I see some images or vdos @Tushar-go
you want me to add images?

**Comment by nisha331** [comment]
@Tushar-go I meant could u provide few screensort or vdo of how is the page .. here in the comment sectn itself

**Comment by Tushar-go** [comment]
> @Tushar-go I meant could u provide few screensort or vdo of how is the page .. here in the comment sectn itself


https://user-images.githubusercontent.com/110401845/219885466-0fb18a0e-2b90-4759-ac0f-4372e53495bf.mp4

**Review by nisha331 — APPROVED** [review]
good one

**Pull request merged**
