### PR TITLE
added method to display the expected date of next period

### PR DESCRIPTION
**Pull request by ayushanand308**

### CODE REVIEW

**Comment by nisha331** [comment]
@ayushanand308 kindly resolve the conflict

**Comment by ayushanand308** [comment]
I have resolved the conflict. @nisha331

**Comment by nisha331** [comment]
@ayushanand308 issue no?

**Comment by ayushanand308** [comment]
@nisha331  '28'

**Comment by ayushanand308** [comment]
@nisha331  I wanted to kindly remind you to review the PR.

**Review by nisha331 — APPROVED** [review]

**Comment by ayushanand308** [comment]
@nisha331 Thank You!

**Pull request merged**
