### PR TITLE
updated calculator function and also working on pressing enter #6

### PR DESCRIPTION
**Pull request by smitra0916**
image

### CODE REVIEW

**Review by rohhhit31 — COMMENTED** [review]
The same can be done in just 15-18 lines of code.  Want me to change it?

**Comment by smitra0916** [comment]
I think my code is short, simple, easy to understand by other developers AND MOST IMPORTANTLY IT WORKS perfectly fine. 

However any advice of improvement are always welcomed.
@rohhhit31 @nisha331

**Comment by rohhhit31** [comment]
It's not short buddy. If it can be cut down so it's always a good practice to trim the logic. Just a suggestion rest is your choice

**Comment by smitra0916** [comment]
Thanks for your feedback.

However it would be better if u can stop stealing credits on the name of optimising other people's logic, try spotting bugs and do fixes yourselves.

FYI there's a lot of projects out there and a lot to work on. Why not work on them buddy or JUST BECAUSE YOU ONLY KNOW THIS CODE ONLY?😝

**Comment by smitra0916** [comment]
BTW new coder here, nice to talk to u...

Will be happy to collaborate on any project in future

Feel free to contact me
www.instagram.com/sourasish_mvp

**Review by nisha331 — APPROVED** [review]
Good Work. can u place this in a diff js file . the scipt here is becoming quite big .

**Comment by nisha331** [comment]
@smitra1609 one done plz say on the discord

**Comment by smitra0916** [comment]
@nisha331 

Sure I will move the script on external js file in the next commit

**Comment by smitra0916** [comment]
> @smitra1609 one done plz say on the discord

Sry, I dont followed what u said. U want me to say "one done" to jwoc discord? Which channel or server
P.s. 1st timer plz help

**Comment by nisha331** [comment]
> > @smitra1609 one done plz say on the discord
> 
> Sry, I dont followed what u said. U want me to say "one done" to jwoc discord? Which channel or server P.s. 1st timer plz help

OH typo *once..
 Yes I meant that,  but its fine u can leave a comment here aswell.

**Comment by nisha331** [comment]
@smitra1609 done?

**Comment by smitra0916** [comment]
yes i have updated with the external js file from my end.
d3c7ae46100a7f685d4a77a227d73158aec25fc3

this fixes #6 #17

**Pull request merged**
