### PR TITLE
Fix UI of pages

### LINKED ISSUE #67: improve design and look of all the pages
Use a single design for all the pages ovulatn, pregnancy, quiz, health etc.

### PR DESCRIPTION
**Pull request by S-ishita**
Closes #67 
Fixed and made the UI of all pages similar

https://user-images.githubusercontent.com/104543751/222361917-521ce5cb-fbae-445d-8af3-c6cfb12d2463.mp4

https://user-images.githubusercontent.com/104543751/222361874-9474c359-840d-4068-ac6d-3f5f72fa36aa.mp4

### CODE REVIEW

**Comment by nisha331** [comment]
@S-ishita  can we just reduce the header and footer height , and also the spacing between header and heading .. other thn header and and footer everything else looks same .. 
Header should be same as home page .. and when u click on the flow cycle if should redirect to homepage .. footer looks good just reduce te height . 
The box around the txt does not look appealing ,so u can remove it

**Comment by S-ishita** [comment]
> @S-ishita can we just reduce the header and footer height , and also the spacing between header and heading .. other thn header and and footer everything else looks same .. Header should be same as home page .. and when u click on the flow cycle if should redirect to homepage .. footer looks good just reduce te height . The box around the txt does not look appealing ,so u can remove it

Done the changes..also i think that the labels should be changed to be  hard :)

**Comment by nisha331** [comment]
> > @S-ishita can we just reduce the header and footer height , and also the spacing between header and heading .. other thn header and and footer everything else looks same .. Header should be same as home page .. and when u click on the flow cycle if should redirect to homepage .. footer looks good just reduce te height . The box around the txt does not look appealing ,so u can remove it
> 
> Done the changes..also i think that the labels should be changed to be hard :)

Screen shorts or vdos plz
And dont worry abt the label i will do it

**Comment by S-ishita** [comment]
Here's the video


https://user-images.githubusercontent.com/104543751/222877069-fefde013-84ce-49d2-8015-d3ac3bfb9878.mp4

**Comment by nisha331** [comment]
Everything is perfect but if the padding and margin is reduced it will look much more better.

**Comment by S-ishita** [comment]
> Everything is perfect but if the padding and margin is reduced it will look much more better.

Can you please share screenshot of where do you want changes in padding and margin??

**Comment by nisha331** [comment]
WhatsApp Image 2023-03-05 at 14 22 55

@S-ishita this part for all the pages

**Comment by S-ishita** [comment]
Fixed the margin and padding for all

Screenshot from 2023-03-06 00-31-19

**Comment by nisha331** [comment]
great .. Can u plz  resolve the conflicts. I will merge it

**Comment by S-ishita** [comment]
> great .. Can u plz resolve the conflicts. I will merge it

Hey, these conflicts are due to favicon issue  #81 ..i have already  added favicon so you can merge it.

**Review by nisha331 — APPROVED** [review]

**Comment by nisha331** [comment]
@S-ishita u have added the favicon still u will have to resolve the conflicts , without doing that PR wont  be merged

**Pull request closed without merging**
