### PR TITLE
Project Restructured

### PR DESCRIPTION
**Pull request by utkarsh006**
- Solves issue #21 
- Restructured the project
- Deleted all the images and inserted 2 images up till now as mentioned in the discord channel.

## Screenshots
Screenshot (357)

### CODE REVIEW

**Comment by nisha331** [comment]
heyy.. If u put the html file in folder then the website hosted wont work

**Comment by utkarsh006** [comment]
@nisha331 How should I resolve it then?

**Comment by nisha331** [comment]
> @nisha331 How should I resolve it then?

put all css file in css folder and js in js folder .. leave html files as it is..

u will also have to change ta paths of the css file and js file  in the html files..

**Comment by utkarsh006** [comment]
@nisha331 Changes done and paths changed. Kindly Review.

**Review by nisha331 — APPROVED** [review]
cool

**Pull request merged**
