### PR TITLE
added faq section

### PR DESCRIPTION
**Pull request by ArgyPorgy**
added a total of 3 files - faq.html, faq.css and faq.js
although have not added this section to the drop down menu as you said @nisha331 please do check it.

issue no. #24

### CODE REVIEW

**Comment by nisha331** [comment]
Can i have some images and photos  @ArgyPorgy

**Comment by ArgyPorgy** [comment]
Screenshot (1490)
Screenshot (1491)
Screenshot (1492)
here @nisha331

**Comment by ArgyPorgy** [comment]
changed the title to FAQ 
Screenshot (1493)

**Review by nisha331 — APPROVED** [review]
Looks good

**Pull request merged**
