### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by vk20july**
Kindly review my code @nisha331 mam
Issue no: #94 

https://user-images.githubusercontent.com/71543332/223946396-ecca3563-f31f-4293-ad59-b529d6431873.mp4

### CODE REVIEW

**Comment by nisha331** [comment]
I dont even what the footer,  every thing should remain collaped , let explore more look like footer on the page , and yes reduce the height of explore more, like this  . 
image

**Comment by vk20july** [comment]
ok mam

**Comment by vk20july** [comment]
https://user-images.githubusercontent.com/71543332/224386749-6232cde2-f3b3-447d-88d8-d4b87f9def6f.mp4

**Comment by vk20july** [comment]
https://user-images.githubusercontent.com/71543332/224388143-e7f6f3c5-e9ad-4e63-9a15-317a77843342.mp4

**Comment by nisha331** [comment]
great work

**Review by nisha331 — APPROVED** [review]

**Comment by vk20july** [comment]
> great work

thank you mam

**Pull request merged**
